# PYTHON LIBRARIES

NUMPY: allows to perform advanced mathematical and statistical operationa on the object.
    it provides vectorization of mathematical operationa on arrays and matrices

pandas:pandas built only numpy

maplotlib:allows to perform visualization (plotting library in python)
    
scikit-learn: it provides machine learing algorithms:classification,regression, clustering,model validation
        

#to install packages

pip install package name
conda install package name

In [1]:
#Numpy:
#creating Numpy arrays

import numpy as np
array_1d=np.array([11,22,33,44,55])          #1 dimensional array
array_2d=np.array([[10,20,30],[40,50,90]])  # 2 dimensional array
print(array_1d)
print(array_2d)

[11 22 33 44 55]
[[10 20 30]
 [40 50 90]]


In [2]:
# find shape of the array
array_2d.shape

(2, 3)

In [3]:
array_1d.shape

(5,)

In [4]:
#number of dimensions
print(array_1d.ndim)
print(array_2d.ndim)

1
2


In [5]:
## creating numpy array using numpy.arrange

array_1=np.arange(15)
print(array_1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
# creating numpy array using numpy.arange

array_2=np.arange(2,10,2)    ##(start,end,step)
array_2

array([2, 4, 6, 8])

In [7]:
## creating numpy array using numpy.linspace
#generates linear evenly spaced elements between the start and the end

array_3=np.linspace(0,0.75,4)
array_3

array([0.  , 0.25, 0.5 , 0.75])

In [8]:
##numpy array creation via various functions

##numpy.zeros,numpy.ones,numpy.eye,numpy.rand,numpy.random and numpy.empty

##numpy.ones
# produces 3x2 array of 1's.
array_4=np.ones((2,3))
print(array_4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
##numpy,zeros
#produce 3x4 array of zeroes
array_5=np.zeros((2,3))
array_5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
print(array_4+array_5)
print(array_4*array_5)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np
x=np.eye(3)   # there 3 id dimention of square matrix
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#numpy.element
#creating uninitialised array
#rand(m) produces uniformly distributed random numbers with range 0 to m

np.random.seed (200)     # set seed
array_8=np.random.rand(5)
array_8

array([0.94763226, 0.22654742, 0.59442014, 0.42830868, 0.76414069])

In [13]:
arra2=np.diag((2,3,6))
arra2

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 6]])

In [14]:
#numpy.empty
##creating uninitilaised array
#numpy.empty(shape)
import numpy as np
array_10=np.empty((4,3))
array_10

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr_11=np.array([10,11,12,13])
print(arr_11.dtype)
print(type(arr_11))

int32
<class 'numpy.ndarray'>


In [16]:
#default dtype in numpy is float
#change the data type
arr_11=arr_11.astype(float)
arr_11.dtype
arr_11

array([10., 11., 12., 13.])

In [17]:
##Numpy indexing and slicing
##array indices in numpy start at 0
#import numpy as np

arr_1=np.arange(6)
arr_2=np.arange(2,7,1.2)
#print entire array
print(arr_1)
print(arr_2)

[0 1 2 3 4 5]
[2.  3.2 4.4 5.6 6.8]


In [18]:
arr_1[2:]

array([2, 3, 4, 5])

In [19]:
arr_1[::2]

array([0, 2, 4])

In [20]:
#last element
arr_1[-1]

5

In [21]:
#modify value at arr_1[1]
arr_1[1]=8
arr_1

array([0, 8, 2, 3, 4, 5])

In [22]:
array_2d

array([[10, 20, 30],
       [40, 50, 90]])

In [23]:
#[row,coloum]
array_2d[1,2]

90

In [24]:
array_2d[0:2]

array([[10, 20, 30],
       [40, 50, 90]])

In [25]:
array_2d[0:2][0:1,2]#[0:2]means it is a row from index o to 1...........
                    #again[0:1,2] means from the 0th row 2nd index number

array([30])

In [26]:
array_2d[0:2,0:2]    #[0:2,0:2]------> means [row slice,column slice]


array([[10, 20],
       [40, 50]])

In [27]:
array_3=np.array([[10,20,30],[40,50,90],[35,65,76],[90,80,70],[23,34,56]])
array_3

array([[10, 20, 30],
       [40, 50, 90],
       [35, 65, 76],
       [90, 80, 70],
       [23, 34, 56]])

In [28]:
array_3[1:3,0:2]

array([[40, 50],
       [35, 65]])

In [29]:
#extract the value 80
array_3[3][1] #or array_3[3,1]

80

In [32]:
array_3

array([[10, 20, 30],
       [40, 50, 90],
       [35, 65, 76],
       [90, 80, 70],
       [23, 34, 56]])

In [33]:
#extract 2nd position row and 1st positioncolumn
array_3[2,1]

65

#nd coloum position values
array_3[0:4,2]

# INTRODUCTION TO PANDAS
#pandas is a power ful package in python.it is used for data cleaning and manipulating data to get summary insights from the data

#panda basically used to manipulate tabular data, it is ability select columns and filter rows sort data and dp groupby tasks

#pandas has two data structures:series and data frame


series:1 dimen labled array (capable of holding any data type).the axis lables are called "index"
create series by using pandas:pandas.series(data,index)
dataframe:two dimensional array

# to install packages
#pip install package name
#!pip install package name(jupyter notebook)
#conda install package name

In [34]:
import pandas as pd
from pandas import Series,DataFrame

In [35]:
#creating a series object
#general syntax is:
#s=series(data,index)     (or)
#s=pd.series(data,index)


In [36]:
#series from a list
s=Series([1,2,3,4,5])
print(s)
print(s[0])
print(s[2])
print(s.values)
print(s.index)
print(list(s.index))

0    1
1    2
2    3
3    4
4    5
dtype: int64
1
3
[1 2 3 4 5]
RangeIndex(start=0, stop=5, step=1)
[0, 1, 2, 3, 4]


In [37]:
s=Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)
print(s[0])
print(s['a'])
print(s.index)

a    1
b    2
c    3
d    4
e    5
dtype: int64
1
1
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [38]:
#adding one element to the series
s['g']=7
print(s)

a    1
b    2
c    3
d    4
e    5
g    7
dtype: int64


In [39]:
#add 1 to each element in "s"
import pandas as pd
s=pd.Series([8,9,10])
print(s)
x=s+1
print(type(x))
print(x)

0     8
1     9
2    10
dtype: int64
<class 'pandas.core.series.Series'>
0     9
1    10
2    11
dtype: int64


In [40]:
#deleting elements from a series
series1=s.drop(1)    # there drop(x)---->"x" means index value in the series
series1

0     8
2    10
dtype: int64

In [41]:
#more than one element from a series
series2=Series([8,9,10],index=['h','i','j'])
print(series2)
series3=series2.drop(['i','j'])
print(series3)

h     8
i     9
j    10
dtype: int64
h    8
dtype: int64


In [42]:
#series from a dictionary
d={"a":3,"b":4}
d1=Series(d)
d1

a    3
b    4
dtype: int64

In [43]:
#we can make changes to a series in place also
d1['a']=8
d1

a    8
b    4
dtype: int64

# pandas DataFrame
#creating s dataframe
#from a dictionary of lists , dictionaries , series
#from a list of dictionaries

In [44]:
#create empty dataframe
D=DataFrame()
D

Empty DataFrame
Columns: []
Index: []

In [45]:
D1=pd.DataFrame()
D1

Empty DataFrame
Columns: []
Index: []

In [46]:
#dictionary of lists
import pandas as pd
from pandas import DataFrame
d={"price":[19,22,13,54,65],"sales":[600,756,587,859,990]}
frame1=DataFrame(d)
print(frame1)

   price  sales
0     19    600
1     22    756
2     13    587
3     54    859
4     65    990


In [47]:
#Dictioanry of dictionary
d1={'iidt':{"cs":"jagggu","ba":"junnu"},"hotel":{"cs":210,"ba":420}}
print(d1)
frame2=DataFrame(d1)
print(frame2)
    

{'iidt': {'cs': 'jagggu', 'ba': 'junnu'}, 'hotel': {'cs': 210, 'ba': 420}}
      iidt  hotel
cs  jagggu    210
ba   junnu    420


In [48]:
#dictionary of series
import pandas as  pd
from pandas import Series,DataFrame
d2={'price':Series([19,22,13,54,65]),'sales':Series([600,756,587,859,990])}
frame3=DataFrame(d2)
print(frame3)

   price  sales
0     19    600
1     22    756
2     13    587
3     54    859
4     65    990


In [49]:
#list of dictionaries
l1=[{"price":19,"sales":600,"qty":30},{"price":22,"sales":756,"qty":65}]
frame4=DataFrame(l1)
print(frame4)

   price  sales  qty
0     19    600   30
1     22    756   65


In [50]:
#rename(coloumns={'oldname1':'newname','oldname2':'newname2'})
frame1.rename(columns={'price':'base_price','sales':'unit sales'},inplace=True)
frame1

base_price  unit sales
0          19         600
1          22         756
2          13         587
3          54         859
4          65         990

In [51]:
frame4.rename(columns={'price':'base_price','sales':'unit sales'},inplace=True)
frame4

base_price  unit sales  qty
0          19         600   30
1          22         756   65

loc and iloc
#loc method is labled-based,which means that you have to specify rows and coloumns based on their row and column lables
#iloc is integer index based,so you have to specify rows and columns by their integer index

In [56]:
#.loc label index
#.iloc integer index
print(frame1)
frame1.iloc[0]

   base_price  unit sales
0          19         600
1          22         756
2          13         587
3          54         859
4          65         990


base_price     19
unit sales    600
Name: 0, dtype: int64

In [61]:
frame1["base_price"]

0    19
1    22
2    13
3    54
4    65
Name: base_price, dtype: int64

In [62]:
frame1.loc[0:3]

base_price  unit sales
0          19         600
1          22         756
2          13         587
3          54         859

In [63]:
print(frame2)
frame2.loc['ba']

      iidt  hotel
cs  jagggu    210
ba   junnu    420


iidt     junnu
hotel      420
Name: ba, dtype: object

In [66]:
#extract the value 756 from frame
frame1.loc[1]['unit sales']

756

In [67]:
frame1.loc[2]['unit sales']

587

In [84]:
d3=DataFrame({"col1":[1,2,3],'col2':[6,7,8]},index=["a","b","c"])
frame3=d3
frame3


col1  col2
a     1     6
b     2     7
c     3     8

In [85]:
frame3.iloc[1,0]

2

In [72]:
frame3.iloc[[2,0,1]]

col1  col2
2     3     8
0     1     6
1     2     7

In [92]:
df1=DataFrame({"price":[23,45,67], "sales":[3,6,7]},index=["a","b","c"])
print(df1)
df1.loc['a']

   price  sales
a     23      3
b     45      6
c     67      7


price    23
sales     3
Name: a, dtype: int64

In [93]:
df1.loc[['a','c']]

price  sales
a     23      3
c     67      7

In [94]:
df1.iloc[[0,1]]

price  sales
a     23      3
b     45      6

In [95]:
df1.iloc[[0]]['sales']

a    3
Name: sales, dtype: int64

In [98]:
#all values from the sales column
df1.iloc[:,[0]]

price
a     23
b     45
c     67

# ZIP FUNCTION

In [99]:
list1=['first','second','third','fourth']
list2=[56,7,8,9]
print(list(zip(list1,list2)))

[('first', 56), ('second', 7), ('third', 8), ('fourth', 9)]


In [ ]:
zipped=list(zip(list1,list2))
zipped

In [ ]:
#data=list(zipped)
data=pd.DataFrame(zipped,columns=['class','marks'])
print(data)
print(type(data))