In [1]:
  import numpy as np


In [2]:
np.__version__

'1.16.5'

In [3]:
#You can concatenate two or more arrays at once.
#for concatination the arrays should be of same dimension
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [4]:
#You can also use this function to create 2-dimensional arrays.
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [5]:
#Using its axis parameter, you can define row-wise or column-wise matrix
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [8]:
#vstack-----it is a type of concatination used to concatenate when there are arrays of different dimension 
import pandas as pd
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
pd.DataFrame(np.vstack([x,grid]))


0   1   2
0   3   4   5
1   1   2   3
2  17  18  19

In [9]:
#Similarly, you can add an array using np.hstack
import numpy as np
z = np.array([[9,5],[9,5]]) #the ztwo lists present inside should have same no of elements in order to run hstack
z

array([[9, 5],
       [9, 5]])

In [6]:
np.hstack([grid,z])

array([[ 1,  2,  3,  9,  5],
       [17, 18, 19,  9,  5]])

# pandas

In [13]:
import pandas as pd

In [13]:
#create a data frame - dictionary is used here where keys get converted to column names and values to row values.
Country= ['Russia','Colombia','Chile','Equador','Nigeria']
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [15]:
#We can do a quick analysis of any data set using:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [15]:
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [17]:
#Let's sort the data frame by ounces - inplace = True will make changes to the data
#data.sort_values(by=['ounces'],ascending=True,inplace=False)
data.sort_values('ounces',ascending=True,inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [24]:
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [20]:
#create another data with duplicated rows
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [21]:
data.sort_values("k2",ascending=False)

k1  k2
5  two   4
6  two   4
0  one   3
3  two   3
4  two   3
1  one   2
2  one   1

In [22]:
#remove duplicates - ta da! 
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [23]:
#, we can also remove duplicates based on a particular column. Let's remove duplicate values from the k1 column.
data.drop_duplicates(subset="k2")

k1  k2
0  one   3
1  one   2
2  one   1
5  two   4

In [24]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [25]:
x=data.assign(new_variable = data['ounces']*10,rate=np.arange(10,27,2))
x

food  ounces  new_variable  rate
0        bacon     4.0          40.0    10
1  pulled pork     3.0          30.0    12
2        bacon    12.0         120.0    14
3     Pastrami     6.0          60.0    16
4  corned beef     7.5          75.0    18
5        Bacon     8.0          80.0    20
6     pastrami     3.0          30.0    22
7    honey ham     5.0          50.0    24
8     nova lox     6.0          60.0    26

In [26]:
x.drop("rate",axis=1,inplace=True)
x

food  ounces  new_variable
0        bacon     4.0          40.0
1  pulled pork     3.0          30.0
2        bacon    12.0         120.0
3     Pastrami     6.0          60.0
4  corned beef     7.5          75.0
5        Bacon     8.0          80.0
6     pastrami     3.0          30.0
7    honey ham     5.0          50.0
8     nova lox     6.0          60.0

In [50]:
#Series function from pandas are used to create arrays
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [51]:
data.replace(-999, np.nan,inplace=True)
data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [52]:
#We can also replace multiple values at once.
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace([-999,-1000],np.nan,inplace=True)
data

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [56]:
#data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                 ['Ohio', 'Colorado', 'New York'],
                    ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [55]:
#Using rename function
#data.rename(index = {'Ohio':'SanF'}, columns={'one':'one_p','two':'two_p'},inplace=True)
#Using rename function
data.rename({'Ohio':'SanF'},{'one':'one_p','two':'two_p'},inplace=True)
data

H:\anaconda\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Interpreting call
	'.rename(a, b)' as 
	'.rename(index=a, columns=b)'.
Use named arguments to remove any ambiguity. In the future, using positional arguments for 'index' or 'columns' will raise  a 'TypeError'.
  after removing the cwd from sys.path.


one_p  two_p  three  four
SanF          0      1      2     3
Colorado      4      5      6     7
New York      8      9     10    11

In [57]:
#You can also use string functions
data.rename(index = str.upper, columns=str.title,inplace=True)
data

One  Two  Three  Four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [29]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [30]:
#Understand the output - '(' means the value is included in the bin, '[' means the value is excluded
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [31]:
#To include the right bin value, we can do:
pd.cut(ages,bins,right=True)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [32]:
#Let's check how many observations fall under each bin
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [34]:
bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
new_cats = pd.cut(ages, bins,labels=bin_names)
pd.value_counts(new_cats)



Youth         5
MiddleAge     3
YoungAdult    3
Senior        1
dtype: int64

In [72]:
#we can also calculate their cumulative sum
pd.value_counts(new_cats).cumsum()

Youth          5
MiddleAge      8
YoungAdult    11
Senior        12
dtype: int64

In [73]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  0.063959 -0.226942
1    a  two  0.716536  2.113498
2    b  one -1.417274 -0.291555
3    b  two -0.683037  0.478939
4    a  one  0.213113  0.132218

In [77]:
#calculate the mean of data1 column by key1
grouped = df['data1'].groupby(df['key1'])
grouped.mean()

key1
a    0.331203
b   -1.050155
Name: data1, dtype: float64

In [36]:
#create a data frame
data = pd.DataFrame({'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [37]:
#calculate means of each group
data.pivot_table(values='ounces',index='group',aggfunc=np.mean)


ounces
group          
a      6.333333
b      7.166667
c      4.666667

In [38]:
#calculate count by each group
data.pivot_table(values='ounces',index='group',aggfunc='count')

ounces
group        
a           3
b           3
c           3